name: CI Pipeline

on:
  issue_comment:
    types: [created]

jobs:
  ci:
    name: Lint, Type Check, and Build
    # Hanya berjalan jika komentar dilakukan di dalam Pull Request dan mengandung teks "/run-ci"
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/run-ci') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v7
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type Check
        run: pnpm run check-types

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
